export const DEPARTMENTS = [
  'Accounting & Information System',
  'Anthropology',
  'Bangla',
  'Biochemistry & Molecular Biology',
  'Botany',
  'Chemistry',
  'Computer Science & Engineering',
  'Economics',
  'English',
  'Film & Television',
  'Finance',
  'Fine Arts',
  'Genetic Engineering & Biotechnology',
  'Geography & Environment',
  'History',
  'Institute of Education & Research',
  'Institute of Modern Languages',
  'Islamic History & Culture',
  'Islamic Studies',
  'Law and Land Administration',
  'Law',
  'Management Studies',
  'Marketing',
  'Mass Communication & Journalism',
  'Mathematics',
  'Microbiology',
  'Music',
  'Pharmacy',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Administration',
  'Social Work',
  'Sociology',
  'Statistics',
  'Theatre',
  'Zoology',
]
